#define WIN32_LEAN_AND_MEAN
#define STRICT
#define DIRECTINPUT_VERSION 0x0700
#define _X86_

#include <windows.h>
#include <windowsx.h>
#include <stdlib.h>		  
#include <stdio.h>
#include <stdarg.h>
#include <math.h>
#include <mmsystem.h>
#include <process.h>
#include <time.h>
#include <memory.h>
#include <string.h>

#include "assert.h"
#include "crtdbg.h"

#include <ddraw.h>
#include <d3d.h>
#include <dinput.h>
#include <dsound.h>

#include "STYPES.H"