#ifndef CODEWAD_H
#define CODEWAD_H

extern void RelocFunc_006(); // called in ControlPhase
extern void RelocFunc_010(); // called in joby7_control
extern void RelocFunc_015(); // special1_init
extern void RelocFunc_016(); // special1_control
extern void RelocFunc_017(); // special1_end
extern void RelocFunc_018(); // special2_init
extern void RelocFunc_019(); // special2_control
extern void RelocFunc_020(); // special2_end
extern void RelocFunc_021(); // special3_init
extern void RelocFunc_022(); // special3_control
extern void RelocFunc_023(); // special3_end
extern void RelocFunc_024(); // special4_init
extern void RelocFunc_025(); // special4_control
extern void RelocFunc_026(); // special4_end

#endif