#include "SPOTCAM.H"

int bUseSpotCam;
int bDisableLaraControl;
int bTrackCamInit;
char SCOverlay;
char SCNoDrawLara;
char SniperOverlay;
short spotcam_timer;
int bCheckTrigger;
short LastSequence;
short CurrentFov;
short spotcam_loopcnt;
short number_spotcams;
struct SPOTCAM* SpotCam;
unsigned char CameraCnt[16];
unsigned char SpotRemap[16];
long current_spline_position;
short LastFov;
int CameraFade;
int LaraHealth;
int LaraAir;
long camera_xposition[18];
long camera_yposition[18];
long camera_zposition[18];
long camera_xtarget[18];
long camera_ytarget[18];
long camera_ztarget[18];
long camera_roll[18];
long camera_fov[18];
long camera_speed[18];
short current_spline_camera;
short current_camera_cnt;
short current_sequence;
short first_camera;
short last_camera;
int spline_from_camera;
int spline_to_camera;
struct PHD_VECTOR InitialCameraPosition;
struct PHD_VECTOR InitialCameraTarget;
struct PHD_VECTOR LaraFixedPosition;
short InitialCameraRoom;
struct QUAKE_CAM quakecam;