#ifndef TEXT_S_H
#define TEXT_S_H

#include "TYPES.H"

extern long GetStringLength(char* string, unsigned short* a1, unsigned short* a2);
extern void GetStringDimensions(char* string, unsigned short* w, unsigned short* h);
extern void DrawChar(unsigned short a0, unsigned short a1, unsigned short a2, struct CHARDEF* a3);
extern char aUEAAAAEEEAAEOO[];
extern long word_9230E;
extern char loc_92020[];
#endif