#ifndef TYPEDEFS_H
#define TYPEDEFS_H

typedef unsigned char uint8;
typedef signed char sint8;
typedef unsigned short uint16;
typedef signed short sint16;
typedef unsigned long uint32;
typedef signed long sint32;
//typedef char bool;
typedef void VOIDFUNCVOID(void);
typedef void VOIDFUNCSINT16(short);
typedef int INTFUNCVOID(void);
typedef int INTFUNCINT(int);
typedef void BLAHVOIDFUNCVOID(void);
typedef int INTFUNCCHARP(char*);
typedef void VOIDFUNCINT(int);
typedef void ROPEFUNC1();
typedef void ROPEFUNC2();
typedef void ROPEFUNC3();
typedef void ROPEFUNC4();
typedef void ROPEFUNC5();
typedef void ROPEFUNC6();
typedef void SUBSUITFUNC1();
typedef void SUBSUITFUNC2();
typedef void BLOCKFUNC();
typedef void BLOCKFUNC2();
typedef long RATFUNC1();
typedef long SPIDERFUNC1();
typedef void TWOGUNFUNC2();
typedef void TWOGUNFUNC();
typedef void HYDRAFUNC2();
typedef void RGFUNC();
typedef void SKELETONFUNC();
typedef void SKELETONFUNC2();
typedef void TOWER2FUNC1();
typedef void TOWER2FUNC2();
typedef void TOWER2FUNC3();
typedef void JOBY2FUNC1();
typedef void JOBY2FUNC2();

#endif