if(EMSCRIPTEN)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -s USE_SDL=2 --emrun -s ASSERTIONS=2 --std=c++11 --preload-file ${ROOT_DIR}/EMSCRIPTEN/ASSETS@/ -s USE_WEBGL2=1 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1")
set(SDL2_LIBRARIES "-s USE_SDL=2")

endif()