#ifndef PSXINPUT_H
#define PSXINPUT_H

#if 0
static struct pad_configs pad_cons[5];
extern unsigned char DualShock;
extern unsigned char PadConnected;
extern short reset_count;
extern char SayNoCount;
static unsigned char align[6];
extern long input;
extern long dbinput;
extern long dbinput2;
extern long inputBusy;
extern long RawPad;
extern long RawEdge;
extern unsigned char Motors[2];
extern long LaraLookY;
extern long LaraLookX;
extern struct ControllerPacket GPad1;
extern struct ControllerPacket GPad2;
extern unsigned long Edge2;
extern struct GouraudBarColourSet healthBarColourSet;
extern struct GouraudBarColourSet poisonBarColourSet;
extern struct GouraudBarColourSet airBarColourSet;
extern struct GouraudBarColourSet dashBarColourSet;
#endif

#endif